### ISSUE TITLE
Global high level controller based on center of mass

### ISSUE THREAD

**Issue by Prakyathkantharaju** [Prakyathkantharaju/Quadruped#5]
## Objective
- use the velocity as an input to the car in the complex env.
- Replicate the same with the quadruped.

## Algorithm
- PPO

## Reward functions (Still thinking about it ). 
- Forward velocity in a hallway (lateral distance constraint, and just move forward )

## Observation 
- Two range finder sensors
- intrinsic readings imu data.

## Tasks to do:
- [x] Make a mapping for the robot space to the com velocity trajectory.
- [ ] Make a vectorized env with the robot moving.
- [ ] Tune hyper parameters.
- [ ] Test it in the mujoco ant with com control -> to position control.
- [ ] Test this in the hardware.
- [ ] Write the report.
