### ISSUE TITLE
COM based line following controller.

### ISSUE THREAD

**Issue by Prakyathkantharaju** [Prakyathkantharaju/Quadruped#6]
## Objective
COM based line following controller

## Algorithm
A2C or PPO

## Reward
stay in the center of the line with high velocity.

## observation
- center line.
- imu ?

## action:
- $v_x$ and $v_y$ of the COM trajectory.

## Task
- [x] Map the control from the COM domain to the robot domain.
- [x] Create the env and train with the PPO.
- [x] Hyperparameter optimization.
- [x] ~~Train and apply it on the ant, and other envs~~
- [x] Test on the car and hopper robots.

**Comment by Prakyathkantharaju** [comment]
The training is working for the regular car envs. I need to tune the hyperparameters still.

https://user-images.githubusercontent.com/34353557/179424969-65b4c854-9573-44a9-acb8-a0435ab19813.mp4

**Comment by Prakyathkantharaju** [comment]
update with new cost function.  More information about that here:
https://github.com/Prakyathkantharaju/Quadruped/blob/main/docs/Reward.md

**Comment by Prakyathkantharaju** [comment]
The reward works very well.
![image](https://user-images.githubusercontent.com/34353557/180695744-fafd6d99-ba11-4730-b4c9-9c368b6a8503.png)

**Comment by Prakyathkantharaju** [comment]
Here is the video for it working, Speed up by 10x

https://user-images.githubusercontent.com/34353557/182052718-547454bc-7dec-4d4d-850c-c3809ef8b39b.mp4
